apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: tictactoe
spec:
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tictactoe
  targetCPUUtilizationPercentage: 20
status:
  currentReplicas: 0
  desiredReplicas: 0
