apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo Hello from Kubernetes
        apt-get update
        apt-get install -y curl
        curl https://google.com
        sleep 120
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    readinessProbe:
      exec:
        command: ["curl", "-f", "https://google.com"]
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      exec:
        command: ["pgrep", "bash"]
      initialDelaySeconds: 15
      periodSeconds: 10
    volumeMounts:
      - name: data-volume
        mountPath: /data
  volumes:
    - name: data-volume
      emptyDir: {}