apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
    - name: liveness
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10