apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers: 
   - name: redis-container
     image: redis
     command: ["/bin/sh", "-c"]
     args: ["echo hello > /data/t.txt"]
     volumeMounts:
       - name: redis-storage
         mountPath: /data
  volumes:
    - name: redis-storage
      emptyDir: {}