apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-reader
  namespace: dev
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: vamshi
roleRef:
  kind: Role
  name: dev-reader
  apiGroup: rbac.authorization.k8s.io