apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
        - image: nginx
          name: nginx-container
          env:
            - name: app
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: app
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: port