apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - image: busybox
      name: conatiner
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo Port=$PORT
          echo App=$APP
      envFrom:
        - configMapRef:
            name: app-config
  restartPolicy: Never