apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemon
spec:
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
      matchLabels:
        app: monitor